name: MyNance
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  metaballs: ^1.4.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.2
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.2
  image_picker: ^1.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
