// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIipGeOpoDm4cgrnMHamd7mGKO3wLbqzA',
    appId: '1:172758620394:web:d08c41b9c118806c925f93',
    messagingSenderId: '172758620394',
    projectId: 'mydemoapp-36f56',
    authDomain: 'mydemoapp-36f56.firebaseapp.com',
    storageBucket: 'mydemoapp-36f56.appspot.com',
    measurementId: 'G-Y8LTX2B5KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5RWtuR_-ZZEx1-CePYBGjcywmHfR8rA',
    appId: '1:172758620394:android:af0edacfced905be925f93',
    messagingSenderId: '172758620394',
    projectId: 'mydemoapp-36f56',
    storageBucket: 'mydemoapp-36f56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5AlOl1SJmZr8NMDYUILBKCQ67-gJbUo',
    appId: '1:172758620394:ios:8b5fe48e4fa402f9925f93',
    messagingSenderId: '172758620394',
    projectId: 'mydemoapp-36f56',
    storageBucket: 'mydemoapp-36f56.appspot.com',
    iosClientId: '172758620394-ij44ki5ospdpjpdeu742nf65hpt1lr1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX5AlOl1SJmZr8NMDYUILBKCQ67-gJbUo',
    appId: '1:172758620394:ios:fa0a496ce0af46b6925f93',
    messagingSenderId: '172758620394',
    projectId: 'mydemoapp-36f56',
    storageBucket: 'mydemoapp-36f56.appspot.com',
    iosClientId: '172758620394-gg4gkase8ksn0askk1tv5u16bl01lfgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynance.RunnerTests',
  );
}
