// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIipGeOpoDm4cgrnMHamd7mGKO3wLbqzA',
    appId: '1:172758620394:web:d08c41b9c118806c925f93',
    messagingSenderId: '172758620394',
    projectId: 'mydemoapp-36f56',
    authDomain: 'mydemoapp-36f56.firebaseapp.com',
    storageBucket: 'mydemoapp-36f56.appspot.com',
    measurementId: 'G-Y8LTX2B5KV',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5RWtuR_-ZZEx1-CePYBGjcywmHfR8rA',
    appId: '1:172758620394:android:257a13d80212de71925f93',
    messagingSenderId: '172758620394',
    projectId: 'mydemoapp-36f56',
    storageBucket: 'mydemoapp-36f56.appspot.com',
  );
}
